# Generated by Django 5.0.6 on 2024-05-16 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmo', '0004_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Izoh')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmo.blogpost', verbose_name='Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Izoh ',
                'verbose_name_plural': 'Izohlar',
            },
        ),
    ]
