# Generated by Django 5.0.6 on 2024-06-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmo', '0005_blogreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogreview',
            options={'verbose_name': 'Blog izoh ', 'verbose_name_plural': 'Blog izohlari'},
        ),
    ]
